version: "3.3"

services:
  minidlna:
    restart: always
    networks:
      lan:
        ipv4_address: "${NETWORK_DLNA_IP}"
    image: "vladgh/minidlna:1.2.0"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "MINIDLNA_MEDIA_DIR=/media"
    volumes:
      - "./data:/media:ro"

networks:
  lan:
    driver: macvlan
    driver_opts:
      parent: "${NETWORK_ADAPTER}"
    ipam:
      config:
        - subnet: "${NETWORK_SUBNET}"